title: Learn to Code
email: hello@learn2code.monster
description: Learn to Code
baseurl: /
url: 'https://learn2code.monster'
twitter_username: null
github_username: null
theme: minima
plugins:
  - jekyll-feed
